### PR TITLE
Update `time` crate to 0.3.36

### PR DESCRIPTION
**Pull request by pbsds**
When compiling with rust 1.80.1 I [get](https://cache.nixos.org/log/ydrzpvxim5faygf4kgqip24mwkidgkml-polaris-0.14.2.drv):

```
   Compiling time v0.3.28
error[E0282]: type annotations needed for `Box<_>`
  --> /build/polaris-0.14.2-vendor.tar.gz/time/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
```

Likely caused by the unfixable regression https://github.com/rust-lang/rust/issues/127343 as reported by @\allysais in https://github.com/NixOS/nixpkgs/issues/332957, who notes that:

> Most commonly, the required fix is just to update the "time" crate.

This fix is tested working with rust 1.80.1

### CODE REVIEW

**Review by lnicola — APPROVED** [review]

**Comment by agersant** [comment]
Thank you!
